 
INSERT INTO Seminars (Naziv, Opis, Datum, Popunjen) values ('Biostatistika', 
'Statistika - grana primijenjene matematike koja se bavi analizom podataka.\nBiostatistika je primjenjena statistika na području biomedicinskih znanosti. Studenti će upoznati najčešće razdiobe u bio‐znanostima, razumjeti osnove teorije uzoraka, objasniti stohastičku vezu i matematičko modeliranje, znati primijeniti statističke testove te razumjeti njihova rješenja, znati osmisliti te provesti statističku obradu bioloških pokusa.',
'2018-01-22 08:00:00', 0) 

INSERT INTO Seminars (Naziv, Opis, Datum, Popunjen) values ('Mikologija', 
'Mikologija je grana biologije koja izučava gljive, uključjući i njihova genetička i biohemijska svojstva, taksonomiju, upotrebu kod ljudi kao lijekove (penicilin), hranu (pivo, vino, sir, jestive gljive) i enteogense, kao i opasnosti koje dolaze od njih, poput trovanja ili infekcije. Mikologija je multidisciplinarna, jer proučava građu, metabolizam, biohemiju, ekologiju, evoluciju i sistematiku gljiva, oslaljajući se na metode i rezultate i drugih bioloških disciplina.\nOd mikologije je nastala fitopatologija, nauka o bolestima biljaka, i ove dvije grane su i dalje blisko povezane zato što su mnoge gljive biljni patogeni.Gljive su osnova života na Zemlji u svojoj ulozi simbionta (lišajevi su zapravo simbioza između mahovina i gljiva). Važne su i jer razlažu kompleksne organske biomolekule poput lignina, izdržljive komponente drveta. Igraju i važnu ulogu u globalnom ciklusu ugljika. Razne gljive i drugi organizmi koji se često svrstavaju u gljive su često ekonomski i sociološki važne, jer neke izazivaju bolesti životinja kao i biljaka. Nauka o patogenim gljivama naziva se medicinska mikologija.',
'2018-03-27 16:30:00', 0) 

INSERT INTO Seminars (Naziv, Opis, Datum, Popunjen) values ('Biogeografija', 
'Biogeografija je znanost o rasprostranjenosti vrsta obično promatranih od regionalnih do kontinentskih razmjera. Primjer rasprostranjenosti na toj razini može se objasniti kombinacijom povijesnih faktora povezanih s prostorom i izolacijom kopna, povezanih s dostupnom zalihom energije. Klasična biogeografija je dobila uzlet razvitkom molekularne sistematike. Taj je razvoj omogućio znanstvenicima da testiraju teorije o podrijetlu i disperziji populacija (npr. otočnih endema). Dok je primjerice klasična biogeografija mogla nagađati o podrijetlu vrsta na Havajskom otočju, molekularna sistematika je omogućila znanstvenicima da testiraju teorije o srodstvu tih populacija s pretpostavljenim izvorom populacija u Aziji i Sjevernoj Americi. Biogeografija je sintetička znanost usko povezana s geografijom, biologijom, geologijom, klimatologijom i ekologijom.', 
'2018-02-28 12:00:00', 0)
 
INSERT INTO Seminars (Naziv, Opis, Datum, Popunjen) values ('Imunologija', 
'Prijavite se za BESPLATNE jednodnevne osmosatne seminare po čijem završetku isti dan polažete certifikacijski ispit. Imati Google certifikat znači nametnuti se svojim klijentima kao profesionalac koji je uspješno savladao napredne funkcije Googleove platforme AdWords.\nVaši klijenti vrednovat će Vas prema rezultatima konverzija koje za njih osiguravate, a upravo ovdje stečena znanja jamče da ćete znati izvući maksimum iz raspoloživih budžeta za oglašavanje. Tek certifikacijom dajete formalni temelj vašem neprestanom usavršavanju u području internetskog oglašavanja. Ovo je prvi, pravi i nezaobilazni korak ako želite promovirati sebe kao vrhunskog profesionalca na tržištu internetskog marketingImunologija (lat. immunitas - otpornost, neprimljivost; grč. lógos - nauka) je grana biomedicinskih znanosti koja proučava cjelokupnu otpornost organizma na djelovanje stranih tvari, tj. antigena. U pratičnom smislu, imunologija proučava sve oblike obrane domaćina od zaraze i štetne posljedice imunosnog odgovora za domaćina. Suvremena imunologija obuhvaća velik broj disciplina koje istražuju ustrojstva i fiziološke funkcije imunološkog sustava, imunost na zarazu, stanja imunološke preosjetljivosti (alergije), imunološke nedostatnosti (imunodeficijencije), imunološke reakcije na presađivanje i tumor, autoimunosne bolesti, kao i brojne imunodijagnostičke postupke.', 
'2018-02-16 09:30:00', 0)

INSERT INTO Seminars (Naziv, Opis, Datum, Popunjen) values ('Fitopatologija', 
'Fitopatologija (lat. "phyton" = biljka; "pathos" = bolest, patnja; "logos" = nauka) je znanost o biljnim bolestima. Bavi se proučavanjem patogenih mikroorganizama i abiotičkih faktora koji izazivaju biljne bolesti, mehanizmom njihovog nastanka, interakcijom uzroka i oboljele biljke i pronalaženjem mjera za njihovo suzbijanje.\nBolest je patološki proces koji nastaje kao rezultat djelovanja parazita, biljke domaćina i utjecaja faktora sredine. Bolešću se označavaju promjene u morfološkim i fiziološkim osobinama biljaka, koje ugrožavaju njihov razvitak, smanjuju prinos i pogoršavaju kvalitetu i na kraju izazivajući njihovo propadanje. Bolest je serija vidljivih i nevidljivih odgovora biljnih stanica i tkiva na patogene mikroorganizme ili faktore vanjske sredine koji rezultiraju promjenama oblika, funkcije ili integriteta biljaka. Patogeni djeluju na biljku enzimima, toksinima ili regulatorima rasta, kako bi si osigurali hranu. Patološki proces obuhvaća i reakciju biljke na akciju patogena i to u velikoj mjeri zavisi od čimbenika okoline.', 
'2017-12-04 11:45:00', 1)